"""update migration

Revision ID: e7d725b645d0
Revises: bd56a30ffab9
Create Date: 2023-12-06 12:02:14.989016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7d725b645d0'
down_revision = 'bd56a30ffab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_connections')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_connections',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('sender_id', sa.INTEGER(), nullable=True),
    sa.Column('receiver_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=255), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.receiver_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.sender_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
